#!/usr/bin/env node
/**
 * Builds the ad-blocking engine assets for the service worker.
 *
 * 1. Bundles @ghostery/adblocker into a single classic-script file the
 *    service worker can importScripts() (public/adblock/engine.js).
 * 2. Downloads EasyList + EasyPrivacy, pre-compiles them into a serialized
 *    FilterEngine, and inlines it as base64 (public/adblock/data.js) so the
 *    worker can deserialize it synchronously at startup.
 *
 * Run with:
 *   node scripts/update-adblock.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import https from "node:https";
import { build } from "esbuild";
import { FiltersEngine } from "@ghostery/adblocker";

const ENGINE_OUT = new URL("../public/adblock/engine.js", import.meta.url);
const DATA_OUT = new URL("../public/adblock/data.js", import.meta.url);

const ENGINE_SOURCE = [
	["EasyList", "https://easylist.to/easylist/easylist.txt"],
	["EasyPrivacy", "https://easylist.to/easylist/easyprivacy.txt"],
];

const ENGINE_CONFIG = {
	enableCompression: true,
	guessRequestTypeFromUrl: true,
	loadExtendedSelectors: false,
	enableHtmlFiltering: false,
	enableInMemoryCache: false,
};

function download(url) {
	return new Promise((resolve, reject) => {
		https
			.get(url, (res) => {
				if (res.statusCode !== 200) {
					res.resume();
					return reject(
						new Error(`failed to download ${url}: status ${res.statusCode}`)
					);
				}
				let data = "";
				res.setEncoding("utf8");
				res.on("data", (chunk) => (data += chunk));
				res.on("end", () => resolve(data));
			})
			.on("error", reject);
	});
}

await mkdir(fileURLToPath(ENGINE_OUT.parent ?? new URL(".", ENGINE_OUT)), {
	recursive: true,
});

// Bundle the engine for the service worker.
const entry = fileURLToPath(new URL("./adblock-entry.js", import.meta.url));
await build({
	entryPoints: [entry],
	outfile: fileURLToPath(ENGINE_OUT),
	bundle: true,
	format: "iife",
	globalName: "$ghosteryAdblocker",
	target: "es2020",
	minify: true,
	legalComments: "none",
});
console.log("wrote public/adblock/engine.js");

// Build the serialized engine from EasyList + EasyPrivacy.
const sources = await Promise.all(
	ENGINE_SOURCE.map(async ([name, url]) => [name, await download(url)])
);
const filters = sources.map(([, raw]) => raw).join("\n");
const engine = FiltersEngine.parse(filters, ENGINE_CONFIG);
const serialized = Buffer.from(engine.serialize()).toString("base64");

const header = `"use strict";
/**
 * Ad-blocking filter data for the Scramjet service worker.
 *
 * AUTO-GENERATED by scripts/update-adblock.mjs. Do not edit directly.
 * Regenerate with:
 *   node scripts/update-adblock.mjs
 *
 * Contains a serialized FilterEngine compiled from:
${sources.map(([name, raw]) => ` *   - ${name}`).join("\n")}
 */

const ADBLOCK_DATA = "${serialized}";
`;

await writeFile(fileURLToPath(DATA_OUT), header, "utf8");
console.log(
	`wrote public/adblock/data.js (${serialized.length.toLocaleString()} chars)`
);
